### ISSUE TITLE
I want to lift .so file but an error occurs

### ISSUE THREAD

**Issue by sanghwa95** [B2R2-org/B2R2#49]
**Describe the bug**
I want to lift a .so file which is from Android APK file.
But an error occurs.
Other common .so files also occur the same issue.
How can I lift .so file?

**To Reproduce**
1. I used F# script below

open B2R2
open B2R2.FrontEnd

[<EntryPoint>]
let main argv =
  let isa = ISA.OfString "armv8a64"
  let handler = BinHandler.Init (isa, "libapp.so")
  let ins = BinHandler.ParseInstr handler 0UL
  ins.Translate handler.TranslationContext |> printfn "%A"
  0

2. $ dotnet build
3. $ dotnet run
4. Build is successful but an error occurs like below.

**Screenshots**
![image](https://github.com/B2R2-org/B2R2/assets/44187001/68a5bf6a-dd80-4ba8-9936-6105a623ef16)

**Environment (please complete the following information):**
 - OS: Windows11
 - .NET Core version: 7.0.201
 - B2R2 version 0.6.1

**Comment by sangkilc** [comment]
Thanks for the report. Can you share your .so file somewhere?

**Comment by sanghwa95** [comment]
https://github.com/sanghwa95/tmp/blob/main/libapp.so
Above is so file link.
Thank you for quick response.

**Comment by sangkilc** [comment]
I see two problems:

1. You are giving the address 0 to `ParseInstr`, which is an invalid address. You may want to lift only the .text section. For instance:
   ```fsharp
   let isa = ISA.OfString "aarch64"
   let hdl = BinHandle.Init (isa, "libapp.so")
   let sec = hdl.BinFile.GetSections (name=".text") |> Seq.exactlyOne
   let ins = BinHandle.ParseInstr (hdl, sec.Address)
   ```

2. Even with the above code, you will see an error because the text section starts with an invalid instruction. You should be able to confirm this using `objdump` or similar tools. A valid address starts @ `0x120068`. So the following code will work, for instance.
   ```fsharp
   let isa = ISA.OfString "aarch64"
   let hdl = BinHandle.Init (isa, "libapp.so")
   let sec = hdl.BinFile.GetSections (name=".text") |> Seq.exactlyOne
   let ins = BinHandle.ParseInstr (hdl, sec.Address + 0x68UL)
   ins.Translate hdl.TranslationContext
   |> Pp.stmtsToString
   |> printfn "%s"
   ```

So this is not really a bug. You should gracefully handle parsing exceptions for invalid instructions in order to properly lift binaries.

**Comment by sanghwa95** [comment]
Thanks for your kind reply!
